### ISSUE TITLE
Input placeholder dissapears onFocus in Internet Explorer 11

### ISSUE THREAD

**Issue by KitsuneKelso** [nordnet/nordnet-ui-kit#297]
**Bug happens on Internet Explorer 11**

The text input field displays the placeholder as it should before focus (_"ÅÅÅÅMMDDXXX" in the image below_):
![before](https://user-images.githubusercontent.com/13475700/31764979-2c4fb928-b4c3-11e7-8ba8-7bd0c397fdbe.png)

However, when focus is put on the field, the placeholder disappears:
![after](https://user-images.githubusercontent.com/13475700/31765004-3d48c99a-b4c3-11e7-9491-87ad02aab173.png)

**Comment by mlenser** [comment]
This is a known IE 11 issue unrelated to ui-kit. See https://social.msdn.microsoft.com/Forums/en-US/169513d0-d1f2-437a-9118-783dc7e19d66/in-ie11-browser-placeholder-text-for-any-input-text-disappears-on-focus?forum=iewebdevelopment

Side note: Placeholders are not great ways of providing lasting data. On other browsers this issue is apparent when 1 character is entered and then the user forgets the format they they need to enter. For cases of formatting an input mask is the best choice. For other cases having the placeholder move out of the input as it does in material design is a good choice.

Closing this as it's an IE 11 bug with inputs and shouldn't be addressed here.
