### ISSUE TITLE
Buttons' focus CSS state in Safari and FF not working

### ISSUE THREAD

**Issue by amerjx** [nordnet/nordnet-ui-kit#299]
Buttons work perfectly fine on Chrome but not Safari or Firefox.

**Chrome**
![chrome](https://user-images.githubusercontent.com/6088322/31812647-f1221618-b583-11e7-87bf-35424ee5ed07.gif)

**Firefox** 
![firefox](https://user-images.githubusercontent.com/6088322/31812648-f14edc16-b583-11e7-97e3-5fc6ce20843a.gif)

**Safari**
![safari](https://user-images.githubusercontent.com/6088322/31812650-f17c69f6-b583-11e7-86a2-406e872408ca.gif)

**Comment by bstream** [comment]
The actual focus states *should* work in all those browsers (I will include a recording for macOS). However, triggering focus with a click depends on OS and browser. See this table for more info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

**Comment by DavidTatti** [comment]
But the Buttons behave like toggles rather than "normal" buttons. So something is very wrong in this if it is supposed to be a Button?

And the very different behaviour across browsers is just weird honestly. The point with a library like this is usually to make sure things behave accordingly. Even though conforming to certain browsers can be a feature in itself.
But it's hard to see that when a Button acts like a Toggle.

**Comment by iamstarkov** [comment]
> And the very different behaviour across browsers is just weird honestly.

it is.

**Comment by bstream** [comment]
Closing this as it is depending on OS / Browser.
