### ISSUE TITLE
Spinner not receiving mask

### ISSUE THREAD

**Issue by KitsuneKelso** [nordnet/nordnet-ui-kit#70]
When creating a `<Spinner />` it is not receiving the mask property for some reason, i.e. the default one:
`mask: url("#spinner__mask--16-2-20");`

Here's what the Styles tab is showing:
![screenshot 2016-08-04 13 35 32](https://cloud.githubusercontent.com/assets/13475700/17400523/aba82984-5a48-11e6-85b4-88597ab7be41.png)

As opposed to what it should look like, and the way it does on the documentation page:
![screenshot 2016-08-04 13 38 34](https://cloud.githubusercontent.com/assets/13475700/17400534/c3b52ae0-5a48-11e6-961d-d775033b9e2a.png)

**Comment by KitsuneKelso** [comment]
This is caused by the vendor.bundle we are using setting the version of React externally to `0.14.7` instead of allowing usage of the local version.

The spinner was written to use the improved .SVG features in React 15 and will not work currently for version 14.

**Comment by GU5TAF** [comment]
I see, will look into making the spinner support React 0.14.x unless you want to take a stab at it and submit a PR? essentially we have to render the svg as a string then use [dangerouslySetInnerHTML](https://facebook.github.io/react/tips/dangerously-set-inner-html.html) to inject it into the spinner div instead of using jsx for the svg.

**Comment by KitsuneKelso** [comment]
I can give it a try if I get the time! :)

**Comment by GU5TAF** [comment]
Confirmed working with React 0.0.14 after 696fa238493c2b753ae9e6ec85df2a44f785a924
